
site_name: Altera-FPGA Site 
repo_url: https://github.com/altera-fpga
repo_name: altera-fpga

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: custom
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.indexes
    - toc.integrate
    - toc.follow
extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
    default: altera-2024.1
  symlinks:
    - src: 'driver-list/driver-list-linux.md'
      dests:
        - 'driver-list_linux/index.md'
    - src: 'driver-list/driver-list-zephyr.md'
      dests:
        - 'driver-list_zephyr/index.md'
    - src: 'driver-list/driver-list-baremetal.md'
      dests:
        - 'driver-list_baremetal/index.md'
    - src: 'driver-list/driver-list-all.md'
      dests:
        - 'driver-list_all/index.md'
  social:
    - icon: material/web  
      link: https://www.altera.com 
    - icon: fontawesome/brands/github 
      link: https://github.com/altera-fpga  
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/altera-fpga/
      

extra_javascript:
  - https://unpkg.com/tablefilter@0.7.3/dist/tablefilter/tablefilter.js
  - assets/tables.js


plugins:
  - git-revision-date-localized:
      enable_creation_date: true  
  - glightbox
  - search:
      lang: en
  - symlink
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
 # - mkdoxy:
 #      projects:
 #        opae-code:
 #          src-dirs: "docs/sw"
 #          full-doc: True
 #          debug: True
 #          hints: True
 #          doxy-cfg:
 #            FILE_PATTERNS: "*.c *.cc *.cxx *.cpp *.c++ *.java *.h *.hh *.hxx *.hpp *.h++ *.xpm"
 #            RECURSIVE: True
 #            DOXYFILE_ENCODING: "UTF-8"
 #            PROJECT_NAME: "OPAE C API"
#             OPTIMIZE_OUTPUT_FOR_C: True
 #            OPTIMIZE_OUTPUT_JAVA: True
 #            JAVADOC_AUTOBRIEF: True
 #            EXTRACT_ALL: True
#              EXCLUDE_SYMLINKS: True
#             EXCLUDE_PATTERNS: "*/archive/* */.git/*"

# Page tree
nav:
  - Welcome: index.md
#  - All Drivers: 'driver-list_all/index.md'
  - Linux Drivers: 
    - 'driver-list_linux/index.md'          
    - HPS Host Drivers:
      - Clock Manager: linux-embedded/clock_manager/clock_manager.md
      - DMA Controller: linux-embedded/dma/dma.md
      - Error Detection & Correction (EDAC): linux-embedded/edac/edac.md
      - Ethernet 1588 PTP Time of Day Clock: linux-embedded/ptp_tod/ptp_emb_tod.md
      - Ethernet Media Access Controller: linux-embedded/emac/emac.md
      - Ethernet Subsystem FPGA IP MAC Specific Ctrl: linux-embedded/hssi/hssi.md
      - Ethernet Subsystem FPGA IP Tile Specific Ctrl: linux-embedded/hssi_xtile/hssi_xtile.md
      - General Purpose Timers: linux-embedded/apb_timers/apb_timers.md
      - General Purpose I/O (GPIO): linux-embedded/gpio/gpio.md 
      - I2C: linux-embedded/i2c/i2c.md
      - I3C: linux-embedded/i3c/i3c.md
      - Interrupt Controller (GICv3): linux-embedded/interrupt_controller_GICv3/irq_gic_v3.md
      - MSGDMA: linux-embedded/msgdma/msgdma.md 
      - NAND Controller: linux-embedded/nand/nand.md 
      - QSFP Controller: linux-embedded/qsfp/qsfp.md
      - QSPI: linux-embedded/qspi/qspi.md
      - Reset Manager: linux-embedded/reset_manager/reset_manager.md
      - SD/eMMC Controller: linux-embedded/sd-emmc/sd-emmc.md
      - SPI: linux-embedded/spi/spi.md
      - System Manager: linux-embedded/system_manager/system_manager.md
      - System Memory Management Unit: linux-embedded/smmu/smmu.md
      - UART: linux-embedded/uart/uart.md
      - USB 2.0 OTG: linux-embedded/usb2_0_otg/usb_2_0_otg.md
      - Watchdog Timers : linux-embedded/watchdog_timers/watchdog_timers.md
      - Zarlink Clock Synchronizer: linux-embedded/zarlink_clock_synchronizer/zarlink_clock_synchronizer.md
    - PCIe Host Drivers: 
      - Altera 16550 Compatible UART: linux-dfl/uart_16550/uart_16550.md
      - Accelerator Functional Unit: linux-dfl/dfl_afu/dfl_afu.md
      - Board Management Controller: linux-dfl/intel_m10_bmc_core/intel_m10_bmc_core.md
      - Device Feature List: linux-dfl/dfl/dfl.md 
      - Ethernet: linux-dfl/s10hssi/s10hssi.md 
      - Ethernet 1588 PTP Time of Day Clock: linux-dfl/ptp_dfl_tod/ptp_dfl_tod.md     
      - FPGA Management Engine: linux-dfl/dfl_fme/dfl_fme.md
      - PCIe Subsystem : linux-dfl/dfl_pci/dfl_pci.md
      - Memory Interface : linux-dfl/dfl_emif/dfl_emif.md
      - MAX 10 Board Management Controller: linux-dfl/intel_m10_bmc_core/intel_m10_bmc_core.md 
      - SPI: linux-dfl/spi_altera_dfl/spi_altera_dfl.md
      - User space I/O (UIO): linux-dfl/uio_dfl/uio_dfl.md 
# - Zephyr Drivers:
#    - 'driver-list_zephyr/index.md'
#    - HPS Zephyr Drivers:
#      - Arm Silicon Provider (SiP) Services: zephyr-embedded/sip_svc/sip_svc.md
#      - Clock Manager: zephyr-embedded/clock_manager/clock_manager.md
#      - FPGA Bridge: zephyr-embedded/fpga_bridge/fpga_bridge.md
#      - GPIO: zephyr-embedded/gpio/gpio.md
#      - Interrupt Controller (GICv3): zephyr-embedded/GIC/gic.md
#      - Interrupt Latency Calculator: zephyr-embedded/ilc/ilc.md
#      - Power State Coordination Interface (PSCI): zephyr-embedded/psci/psci.md
#      - Quad SPI: zephyr-embedded/qspi/qspi.md
#      - Remote OS Update: zephyr-embedded/remote_os_update/remote_os_update.md
#      - Reset Manager: zephyr-embedded/reset_manager/reset_manager.md
#      - SD/MMC: zephyr-embedded/sd-mmc/sd-mmc.md
#      - Single Error Upset (SEU): zephyr-embedded/seu/seu.md
#      - SPI: zephyr-embedded/spi/spi.md
#      - Timer: zephyr-embedded/timer/timer.md
#      - UART: zephyr-embedded/uart/uart.md
#      - USB 2.0: zephyr-embedded/usb2_0_otg/usb_2_0_otg.md
#      - Watchdog Timer: zephyr-embedded/watchdog/watchdog.md
#  - Bare Metal Drivers:
#    - 'driver-list_baremetal/index.md'
  - Host Attach Utilities:
    - Host Attach Utilities Summary: sw-tools-list/host-attach-tools.md
    - fpgaconf: host-attach-util/fpgaconf/fpgaconf.md
    - fpgad: host-attach-util/fpgad/fpgad.md
    - fpgainfo: host-attach-util/fpgainfo/fpgainfo.md
    - fpgaport: host-attach-util/fpgaport/fpgaport.md
    - fpgasupdate: host-attach-util/fpgasupdate/fpgasupdate.md
    - hssi: host-attach-util/hssi/hssi.md
    - host_exerciser: host-attach-util/host_exerciser/host_exerciser.md
    - HSSI ethernet loopback: host-attach-util/hssi_ethernet/hssimac.md
    - HSSI ethernet statistics: host-attach-util/hssi_ethernet/hssistats.md
    - HSSI ethernet mac: host-attach-util/hssi_ethernet/hssimac.md
    - mem_tg: host-attach-util/mem_tg/mem_tg.md
    - mmlink: host-attach-util/mmlink/mmlink.md
    - ofs.uio: host-attach-util/ofs.uio/ofs.uio.md
    - opae.io: host-attach-util/opae.io/opae.io.md
    - opaeuio: host-attach-util/opaeuio/opaeuio.md
    - opaevfio: host-attach-util/opaevfio/opaevfio.md
    - pac_hssi_config: host-attach-util/pac_hssi_config/pac_hssi_config.md
    - packager: host-attach-util/packager/packager.md
    - pci_device: host-attach-util/pci_device/pci_device.md
    - rsu: host-attach-util/rsu/rsu.md
    - userclk: host-attach-util/userclk/userclk.md
    - vabtool: host-attach-util/vabtool/vabtool.md
  - Example Designs: 
    - Agilex 5:
        - Agilex 5 E-Series Premium Devkit GSRD: embedded-designs/agilex-5/e-series/premium/ug-gsrd-agx5e-premium.md
    




markdown_extensions:
  - pymdownx.snippets
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - mdx_truly_sane_lists

  # Python Markdown Extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true          
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

env: 
# Devices         
  AGILEX: Intel® Agilex® 7 FPGA

