site_name: Altera FPGA Developer Site 
repo_url: https://github.com/altera-fpga
repo_name: altera-fpga
site_url: https://altera-fpga.github.io/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: custom
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.indexes
    - toc.follow
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablefilter@0.7.3/dist/tablefilter/tablefilter.js
  - assets/tables.js
  - assets/extra.js





extra:
  version:
    provider: mike
  symlinks:
    - src: 'driver-list/driver-list-linux.md'
      dests:
        - 'driver-list_linux/index.md'
    - src: 'driver-list/driver-list-zephyr.md'
      dests:
        - 'driver-list_zephyr/index.md'
    - src: 'driver-list/driver-list-baremetal.md'
      dests:
        - 'driver-list_baremetal/index.md'
    - src: 'driver-list/driver-list-all.md'
      dests:
        - 'driver-list_all/index.md'
    - src: 'embedded-designs/agilex-5/e-series/premium/xen/ug-xen-agx5e-premium.md'
      dests:
        - 'virtualization/hypervisors/xen/ug-xen-agx5e-premium.md'
    - src: 'embedded-designs/agilex-5/e-series/modular/xen/ug-xen-agx5e-modular.md'
      dests:
        - 'virtualization/hypervisors/xen/ug-xen-agx5e-modular.md'
    - src: 'embedded-designs/agilex-7/f-series/soc/xen/ug-xen-agx7f-soc.md'
      dests:
        - 'virtualization/hypervisors/xen/ug-xen-agx7f-soc.md'

  social:
    - icon: material/web  
      link: https://www.altera.com 
    - icon: fontawesome/brands/github 
      link: https://github.com/altera-fpga  
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/altera-fpga/


plugins:
  - git-revision-date-localized:
      enable_creation_date: true  
  - glightbox
  - search:
      lang: en
  - symlink
  - mike:      
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
 # - mkdoxy:
 #      projects:
 #        opae-code:
 #          src-dirs: "docs/sw"
 #          full-doc: True
 #          debug: True
 #          hints: True
 #          doxy-cfg:
 #            FILE_PATTERNS: "*.c *.cc *.cxx *.cpp *.c++ *.java *.h *.hh *.hxx *.hpp *.h++ *.xpm"
 #            RECURSIVE: True
 #            DOXYFILE_ENCODING: "UTF-8"
 #            PROJECT_NAME: "OPAE C API"
#             OPTIMIZE_OUTPUT_FOR_C: True
 #            OPTIMIZE_OUTPUT_JAVA: True
 #            JAVADOC_AUTOBRIEF: True
 #            EXTRACT_ALL: True
#              EXCLUDE_SYMLINKS: True
#             EXCLUDE_PATTERNS: "*/archive/* */.git/*"

# Page tree
nav:
  - Welcome: index.md
#  - All Drivers: 'driver-list_all/index.md'
  - Linux Drivers: 
    - 'driver-list_linux/index.md'          
    - HPS Host Drivers:
      - Altera Hardware Monitor: linux-embedded/hwmon/hwmon.md
      - Clock Manager: linux-embedded/clock_manager/clock_manager.md
      - DMA Controller: linux-embedded/dma/dma.md
      - Error Detection & Correction (EDAC): linux-embedded/edac/edac.md
      - Ethernet 1588 PTP Time of Day Clock: linux-embedded/ptp_tod/ptp_emb_tod.md
      - Ethernet Media Access Controller: linux-embedded/emac/emac.md
      - Ethernet Subsystem FPGA IP MAC Specific Ctrl: linux-embedded/hssi/hssi.md
      - Ethernet Subsystem FPGA IP Tile Specific Ctrl: linux-embedded/hssi_xtile/hssi_xtile.md
      - General Purpose Timers: linux-embedded/apb_timers/apb_timers.md
      - General Purpose I/O (GPIO): linux-embedded/gpio/gpio.md 
      - I2C: linux-embedded/i2c/i2c.md
      - I3C: linux-embedded/i3c/i3c.md
      - Interrupt Controller (GICv3): linux-embedded/interrupt_controller_GICv3/irq_gic_v3.md
      - MSGDMA: linux-embedded/msgdma/msgdma.md 
      - NAND Controller: linux-embedded/nand/nand.md 
      - QSFP Controller: linux-embedded/qsfp/qsfp.md
      - QSPI: linux-embedded/qspi/qspi.md
      - Reset Manager: linux-embedded/reset_manager/reset_manager.md
      - SD/eMMC Controller: linux-embedded/sd-emmc/sd-emmc.md
      - SPI: linux-embedded/spi/spi.md
      - System Manager: linux-embedded/system_manager/system_manager.md
      - System Memory Management Unit: linux-embedded/smmu/smmu.md
      - UART: linux-embedded/uart/uart.md
      - USB 2.0 OTG: linux-embedded/usb2_0_otg/usb_2_0_otg.md
      - Watchdog Timers : linux-embedded/watchdog_timers/watchdog_timers.md
      - Zarlink Clock Synchronizer: linux-embedded/zarlink_clock_synchronizer/zarlink_clock_synchronizer.md
    - PCIe Host Drivers: 
      - Altera 16550 Compatible UART: linux-dfl/uart_16550/uart_16550.md
      - Accelerator Functional Unit: linux-dfl/dfl_afu/dfl_afu.md
      - Board Management Controller: linux-dfl/intel_m10_bmc_core/intel_m10_bmc_core.md
      - Device Feature List: linux-dfl/dfl/dfl.md 
      - Ethernet: linux-dfl/s10hssi/s10hssi.md 
      - Ethernet 1588 PTP Time of Day Clock: linux-dfl/ptp_dfl_tod/ptp_dfl_tod.md     
      - FPGA Management Engine: linux-dfl/dfl_fme/dfl_fme.md
      - PCIe Subsystem : linux-dfl/dfl_pci/dfl_pci.md
      - Memory Interface : linux-dfl/dfl_emif/dfl_emif.md
      - MAX 10 Board Management Controller: linux-dfl/intel_m10_bmc_core/intel_m10_bmc_core.md 
      - SPI: linux-dfl/spi_altera_dfl/spi_altera_dfl.md
      - User space I/O (UIO): linux-dfl/uio_dfl/uio_dfl.md
  - Zephyr Drivers:
    - 'driver-list_zephyr/index.md'
    - HPS Zephyr Drivers:
      - Clock Manager: zephyr-embedded/clock_manager/clock_manager.md
      - Cold & Warm Reset -Power State Coordination Interface (PSCI): zephyr-embedded/psci/psci.md
      - DMA: zephyr-embedded/dma/dma.md
      - General Purpose Timer: zephyr-embedded/timer/timer.md
      - GPIO: zephyr-embedded/gpio/gpio.md
      - Quad SPI: zephyr-embedded/qspi/qspi.md
      - Reset Manager: zephyr-embedded/reset_manager/reset_manager.md
      - Single Event Upset (SEU): zephyr-embedded/seu/seu.md
      - SMP: zephyr-embedded/smp/smp.md
      - UART: zephyr-embedded/uart/uart.md
      - Watchdog Timer: zephyr-embedded/watchdog/watchdog.md
  - Virtualization:
      - Hypervisors:
        - Xen:
          - Overview: virtualization/hypervisors/xen/xen-overview.md
          - Examples:
            - Agilex™ 5 E-Series Premium Development Kit Xen Hypervisor GSRD: virtualization/hypervisors/xen/ug-xen-agx5e-premium.md
            - Agilex™ 5 E-Series Modular Development Kit Xen Hypervisor GSRD: virtualization/hypervisors/xen/ug-xen-agx5e-modular.md
            - Agilex™ 7 F-Series SoC Development Kit Xen Hypervisor GSRD: virtualization/hypervisors/xen/ug-xen-agx7f-soc.md
  - Baremetal Drivers:
    - 'driver-list_baremetal/index.md'
  - Host Attach Utilities:
    - Host Attach Utilities Summary: sw-tools-list/host-attach-tools.md
    - fpgaconf: host-attach-util/fpgaconf/fpgaconf.md
    - fpgad: host-attach-util/fpgad/fpgad.md
    - fpgainfo: host-attach-util/fpgainfo/fpgainfo.md
    - fpgaport: host-attach-util/fpgaport/fpgaport.md
    - fpgasupdate: host-attach-util/fpgasupdate/fpgasupdate.md
    - hssi: host-attach-util/hssi/hssi.md
    - host_exerciser: host-attach-util/host_exerciser/host_exerciser.md
    - HSSI ethernet loopback: host-attach-util/hssi_ethernet/hssimac.md
    - HSSI ethernet statistics: host-attach-util/hssi_ethernet/hssistats.md
    - HSSI ethernet mac: host-attach-util/hssi_ethernet/hssimac.md
    - mem_tg: host-attach-util/mem_tg/mem_tg.md
    - mmlink: host-attach-util/mmlink/mmlink.md
    - ofs.uio: host-attach-util/ofs_uio/ofs_uio.md
    - opae.io: host-attach-util/opae_io/opae_io.md
    - opaeuio: host-attach-util/opaeuio/opaeuio.md
    - opaevfio: host-attach-util/opaevfio/opaevfio.md
    - pac_hssi_config: host-attach-util/pac_hssi_config/pac_hssi_config.md
    - packager: host-attach-util/packager/packager.md
    - pci_device: host-attach-util/pci_device/pci_device.md
    - rsu: host-attach-util/rsu/rsu.md
    - userclk: host-attach-util/userclk/userclk.md
    - vabtool: host-attach-util/vabtool/vabtool.md
  - Example Designs:
    - Summary: ed-demo-list/ed-list.md
    - Agilex™ 5:
      - E-Series Premium Development Kit:
        - GSRD User Guide: embedded-designs/agilex-5/e-series/premium/gsrd/ug-gsrd-agx5e-premium.md
        - Zephyr GSRD User Guide: embedded-designs/agilex-5/e-series/premium/gsrd_zephyr/ug-zgsrd-agx5e-premium.md
        - GHRD Linux Boot Examples: embedded-designs/agilex-5/e-series/premium/boot-examples/ug-linux-boot-agx5e-premium.md
        - TSN Examples:
          - TSN - HPS RGMII System: embedded-designs/agilex-5/e-series/premium/tsn/rgmii-hps/ug-tsncfg1-agx5e-premium.md
          - TSN - SGMII XCVR System: embedded-designs/agilex-5/e-series/premium/tsn/sgmii_xcvr/ug-tsn-sgmii-xcvr-agilex5.md
        - FPGA Remote Debug Example: embedded-designs/agilex-5/e-series/premium/remote-debug/ug-remote-debug-agx5e-premium.md
        - SoC HPS Remote System Update Example: embedded-designs/agilex-5/e-series/premium/rsu/ug-rsu-agx5e-soc.md
        - Xen Hypervisor GSRD: embedded-designs/agilex-5/e-series/premium/xen/ug-xen-agx5e-premium.md
      - E-Series Modular Development Kit:
        - GSRD User Guide: embedded-designs/agilex-5/e-series/modular/gsrd/ug-gsrd-agx5e-modular.md
        - GHRD Linux Boot Examples: embedded-designs/agilex-5/e-series/modular/boot-examples/ug-linux-boot-agx5e-modular.md
        - Xen Hypervisor GSRD: embedded-designs/agilex-5/e-series/modular/xen/ug-xen-agx5e-modular.md
      - Intel Simics Virtual Platform Examples:
        - Linux GSRD: embedded-designs/agilex-5/common/virtual-platforms/linux-gsrd/ug-linux-gsrd-agilex5-virtual-platforms.md
        - Zephyr GSRD: embedded-designs/agilex-5/common/virtual-platforms/zephyr-gsrd/ug-zephyr-gsrd-agilex5-virtual-platforms.md
    - Agilex™ 7:
      - F-Series SoC Development Kit:
        - GSRD User Guide: embedded-designs/agilex-7/f-series/soc/gsrd/ug-gsrd-agx7f-soc.md
        - SoC HPS Remote System Update Example: embedded-designs/agilex-7/f-series/soc/rsu/ug-rsu-agx7f-soc.md
        - SoC HPS Multi-QSPI Remote System Update Example: embedded-designs/agilex-7/f-series/soc/rsu/ug-rsu-multiqspi-agx7f-soc.md
        - SoC FPGA Remote Debug Example: embedded-designs/agilex-7/f-series/soc/remote-debug/ug-remote-debug-agx7f-soc.md
        - HPS eMMC Boot Example: embedded-designs/agilex-7/f-series/soc/emmc/ug-emmc-agx7f-soc.md
        - SoC Fabric Configuration from Linux Example: embedded-designs/agilex-7/f-series/soc/fabric-config/ug-linux-fabric-config-agx7f-soc.md
        - GHRD Linux Boot Examples: embedded-designs/agilex-7/f-series/soc/boot-examples/ug-linux-boot-agx7-soc.md
        - Xen Hypervisor GSRD: embedded-designs/agilex-7/f-series/soc/xen/ug-xen-agx7f-soc.md
      - F-Series FPGA Development Kit:
        - GSRD User Guide: embedded-designs/agilex-7/f-series/fpga/gsrd/ug-gsrd-agx7f-fpga.md       
      - I-Series FPGA Development Kit:
        - GSRD User Guide: embedded-designs/agilex-7/i-series/soc/gsrd/ug-gsrd-agx7i-soc.md
      - M-Series HBM2e Development Kit:
        - GSRD User Guide: embedded-designs/agilex-7/m-series/hbm2e/ug-gsrd-agx7m-hbm2e.md
        - PCIe Root Port User Guide: embedded-designs/agilex-7/m-series/pcie_rp/ug-pcie_rp-agx7m-hbm2e.md
    - Stratix® 10:
      - SX SoC Development Kit:
        - GSRD User Guide: embedded-designs/stratix-10/sx/soc/gsrd/ug-gsrd-s10sx-soc.md
        - SoC HPS Remote System Update Example: embedded-designs/stratix-10/sx/soc/rsu/ug-rsu-s10sx-soc.md
        - SoC FPGA Remote Debug Example: embedded-designs/stratix-10/sx/soc/remote-debug/ug-remote-debug-s10sx-soc.md
        - HPS eMMC Boot Example: embedded-designs/stratix-10/sx/soc/emmc/ug-emmc-s10sx-soc.md
        - SoC Fabric Configuration from Linux Example: embedded-designs/stratix-10/sx/soc/fabric-config/ug-linux-fabric-config-s10sx-soc.md
        - GHRD Linux Boot Examples: embedded-designs/stratix-10/sx/soc/boot-examples/ug-linux-boot-s10-soc.md
  - Demos:
    - Summary: ed-demo-list/demo-list.md
    - Agilex™ 5:
      - E-Series Premium Development Kit:
        - Baremetal Hello World Example: baremetal-embedded/agilex-5/e-series/premium/ug-baremetal-agx5e-premium.md
        - Third Party Boards - HPS-FPGA Interfaces Demos User Guide: https://github.com/altera-fpga/agilex5-demo-hps2fpga-interfaces/blob/main/documentation/01_index.md
        - Debugging U-Boot with Arm Development Studio: demos/agilex-5/e-series/premium/armds-debug-uboot/ug-armds-debug-uboot-agx5e-premium.md
        - Debugging U-Boot with Ashling RiscFree: demos/agilex-5/e-series/premium/riscfree-debug-u-boot/ug-riscfree-debug-uboot-agx5e-premium.md
        - Debugging Linux with Ashling RiscFree: demos/agilex-5/e-series/premium/riscfree-debug-linux/ug-riscfree-debug-linux-agx5e-premium.md
        - Debugging Linux with Arm Development Studio: demos/agilex-5/e-series/premium/armds-debug-linux/ug-armds-debug-linux-agx5e-premium.md

markdown_extensions:
  - pymdownx.snippets
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - mdx_truly_sane_lists

  # Python Markdown Extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true          
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

ignorefiles:
  docs/doc_modules/
  docs/embedded-designs/doc_modules/

env: 
# Devices         
  AGILEX: Intel® Agilex® 7 FPGA
  ALTERA_RELEASE: rel-24.3.1

# Variables for content supported by current release  
  COMMON_QUARTUS_VER_L: Quartus<sup>&reg;</sup> Prime Pro Edition Version 24.3.1
  COMMON_QUARTUS_VER_S: 24.3.1
  PREV_COMMON_QUARTUS_VER_S: 24.3
  GSRD_LINUX_BRANCH_S: 6.6.51-lts
  GSRD_UBOOT_BRANCH_S: 2024.07
  GSRD_ATF_BRANCH_S: 2.11.1
  GSRD_LINUX_BRANCH: socfpga-6.6.51-lts
  GSRD_UBOOT_BRANCH: socfpga_v2024.07
  GSRD_ATF_BRANCH: socfpga_v2.11.1
  GSRD_DATE: 2025.01
  GSRD_TAG: QPDS24.3.1_REL_GSRD_PR
  GSRD_YOCTO_BRANCH: styhead
  GSRD_CMAKE_VER: 3.21.1
  GSRD_ZEPHYR_BRANCH: socfpga_rel_24.3 
  GSRD_ZEPHYR_PRJ_BRANCH: v3.6-branch
  GSRD_ZEPHYR_PRJ_BRANCH_S: 3.6

# Variables for content not supported by current release
  MINOR_COMMON_QUARTUS_VER_L: Quartus<sup>&reg;</sup> Prime Pro Edition Version 24.3
  MINOR_COMMON_QUARTUS_VER_S: 24.3
  MINOR_PREV_COMMON_QUARTUS_VER_S: 24.2
  MINOR_GSRD_LINUX_BRANCH_S: 6.6.37-lts
  MINOR_GSRD_UBOOT_BRANCH_S: 2024.04
  MINOR_GSRD_ATF_BRANCH_S: 2.11.0
  MINOR_GSRD_LINUX_BRANCH: socfpga-6.6.37-lts
  MINOR_GSRD_UBOOT_BRANCH: socfpga_v2024.04
  MINOR_GSRD_ATF_BRANCH: socfpga_v2.11.0
  MINOR_GSRD_DATE: 2024.11
  MINOR_GSRD_TAG: QPDS24.3_REL_GSRD_PR
  MINOR_GSRD_YOCTO_BRANCH: scarthgap
  MINOR_GSRD_CMAKE_VER: 3.21.1
  MINOR_GSRD_ZEPHYR_BRANCH: socfpga_rel_24.3
  MINOR_GSRD_ZEPHYR_PRJ_BRANCH: v3.6-branch
  MINOR_GSRD_ZEPHYR_PRJ_BRANCH_S: 3.6



